language: python
python:
  - "3.3"
  - "3.4"
install:
  - "pip install coverage==3.7.1"
  - "pip install python-coveralls==2.4.2"
  - "pip install -r requirements.txt"
before_script:
  - "coverage erase"
script:
  - "./runtests.sh"
after_success:
  - "coverage report"
  - "coveralls"
